apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-psql-test
  namespace: edu-daniil-vdovin
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    envFrom:
    - secretRef:
        name: postgres
    volumeMounts:
    - name: pg-cert
      mountPath: /etc/postgres-cert
      readOnly: true
  volumes:
  - name: pg-cert
    secret:
      secretName: postgres
      items:
      - key: root.crt
        path: root.crt