apiVersion: batch/v1
kind: Job
metadata:
  name: django-clearsessions
spec:
  template:
    spec:
      containers:
      - name: django
        image: django_app
        imagePullPolicy: Never
        command: ["python", "manage.py", "clearsessions"]
        envFrom:
        - secretRef:
            name: django-app-secrets
      restartPolicy: OnFailure