apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-cron
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django
            image: django_app
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            envFrom:
            - secretRef:
                name: django-app-secrets
          restartPolicy: OnFailure