---
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-service
spec:
  type: NodePort
  selector:
    app: django-k8s
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-k8s
  template:
    metadata:
      labels:
        app: django-k8s
    spec:
      containers:
        - name: django-container
          image: django_app
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DEBUG
              value: "True"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-app-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-app-secrets
                  key: DATABASE_URL