apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
      - name: django-migrate
        image: django_app
        imagePullPolicy: Never
        command: ["python", "manage.py", "migrate"]
        envFrom:
        - secretRef:
            name: django-app-secrets
      restartPolicy: OnFailure